#!/data/data/com.termux/files/usr/bin/bash

YT_DLP_CONFIG_FILE="${HOME}/.config/yt-dlp/config"

yt-dlp --embed-subs --embed-metadata --embed-thumbnail\
-o "~/storage/downloads/%(extractor)s/%(uploader)s/%(title)s%(ext)s" \
--config-location "$YT_DLP_CONFIG_FILE"
